baseURL = 'https://info24.nudawaj.online/'
languageCode = 'en-us'
Title = 'info24'
theme = 'PaperMod'
relativeurls = true

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[params.logo]
        path = "/https://cdn.pixabay.com/photo/2015/10/01/17/17/car-967387_960_720.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
